name: FluxChat
options:
  bundleIdPrefix: com.flux
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift.git
    from: "2.0.0"
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: "12.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"

targets:
  FluxChat:
    type: application
    platform: iOS
    sources:
      - FluxChat
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: FluxChat/Info.plist
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        PRODUCT_BUNDLE_IDENTIFIER: com.flux.app.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.social-networking"
        ENABLE_USER_SCRIPT_SANDBOXING: false
    dependencies:
      - package: LiveKit
        product: LiveKit
      - package: Nuke
        product: NukeUI
      - package: KeychainAccess
